### ISSUE TITLE
eth_getFilterChanges 出现 filter not found 错误

### ISSUE THREAD

**Issue by leoyey** [HuobiGroup/huobi-eco-chain#18] opened 2021-05-07 07:09 UTC
Hi,

使用RPC调用主网（https://http-mainnet-node.huobichain.com/）的eth_getFilterChanges方法，出现  filter not found。操作步骤如下。请问能否修复一下这个问题？

curl --location --request POST 'https://http-mainnet-node.huobichain.com/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "method":"eth_newBlockFilter",
    "params":[],
    "id":128
}'

{"jsonrpc":"2.0","id":128,"result":"0x31558e125c0b6eff8dd403c6429d2b4a"}

-------

curl --location --request POST 'https://http-mainnet-node.huobichain.com/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "method":"eth_getFilterChanges",
    "params":[
        "0x31558e125c0b6eff8dd403c6429d2b4a"
    ],
    "id":128
}'

{"jsonrpc":"2.0","id":128,"error":{"code":-32000,"message":"filter not found"}}

**Comment by wangsai-silence** [comment] 2021-06-30 06:20
Duplicate of #23

**Closed** 2021-06-30 06:19 UTC
